type = "webpack"
name = "html-render-cache"
account_id = "YOUR_ACC_ID"
zone_id = "YOUR_ZONE_ID"
route = "domain.tld/*"
# workers_dev = true  <---- Use this instead of "route" if you want to use {FUNCTION_NAME}.{YOUR_CF_DOMAIN}.workers.dev
webpack_config = "webpack.config.js"

kv-namespaces = [
	{ binding = "HTML_CACHE", id = "YOUR_ID", preview_id = "YOUR_PREVIEW_ID" }
]

vars = { ENDPOINT = "https://www.YOUR_ENDPOINT.com/" } # This is where your pathname will resolve from